if(message.content === prefix + "409"){
	let embed = new Discord.RichEmbed()
	.setColor("0x000000") //Met la couleur noir à gauche de l'embed
	.setThumbnail("https://cdn.discordapp.com/avatars/568437925453234176/7817bef4754c41be03e31f16d47802ff.png?size=2048") //Met le logo SCP en haut à gauche de l'embed
	.setFooter(ftr, authpdp) //Met "Demandé par ..." en bas de l'embed
	.addField("Information", "**Titre:** Cristal Contagieux\n**Objet #:** SCP-409\n**Classe:** Keter")
	.addField("Procédures de Confinement Spéciales", "Aucune personne n'est autorisée à entrer en contact avec SCP-409, ou à faire entrer quoi que ce soit en contact avec SCP-409. Toute chose entrant en contact avec SCP-409, ainsi que tout appareil ayant permis le transport de l'objet, doit être mis en quarantaine immédiatement. SCP-409 doit rester dans une cellule de granit en toute circonstance. Tout déplacement de SCP-409 doit être fait en le transportant dans un conteneur verrouillé fait entièrement en granit. Les résidus des objets ayant été contaminés par SCP-409 doivent être enfermés aussi vite que possible dans un conteneur en granit. La même chose s'applique pour tout outil ayant aidé à apporter les résidus dans le conteneur.")
	.addField("Description", "SCP-409 ressemble à un large cristal de quartz d'une hauteur d'environ 1,5 m et d'une largeur d'environ 0,6 m. Tout objet entrant en contact avec SCP-409 commencera à se cristalliser après trois heures. Cet effet se produira pour n'importe quel matériau, à l'exception du granit. Le processus de cristallisation avancera d'environ 2,5 cm par minute, et convertira l'intégralité de l'objet ou organisme, à l'intérieur et à l'extérieur. Les sujets de test décrivent ce processus comme étant extrêmement douloureux, et comparent la sensation ressentie dans les membres cristallisés à la sensation d'une engelure. Une fois le processus de cristallisation terminé, l'objet se fissurera et émettra des craquements pendant environ 20 minutes, avant d'exploser en mille morceaux.")
	.addField("-", "Tout objet touchant, ou touché par un fragment, commencera à se cristalliser en moins de quatre secondes. À ce jour, aucun moyen n'a été trouvé pour empêcher ce processus; même l'amputation du membre infecté n'est pas suffisante, et le reste du corps continuera à se cristalliser. La matière inorganique se cristallisera sur quelques centimètres autour du point de contact. SCP-409 fut découvert dans [DONNÉES SUPPRIMÉES], enseveli sous un amas de fragments de cristaux, à █ mètres de profondeur. De nombreux membres du personnel furent perdus pendant la récupération de SCP-409.")
	.addField("Annexe 1", "Après une proposition du Dr [500-0021D], le Sujet de test 409-D5 fut exposé aux effets de SCP-409 et fut laissé dans la cellule de celui-ci, jusqu'à ce que plus de la moitié de son corps soit cristallisée. Après cela, il fut soigné avec une pilule de SCP-500. Le sujet fut entièrement soigné après 9 jours. Celui-ci expliqua qu'il continuait à ressentir de fortes douleurs dans les membres qui avaient été cristallisés, en dépit du fait qu'ils avaient apparemment été soignés. Les douleurs s'arrêtèrent 13 jours après le début du traitement. Il est impossible de savoir si les douleurs du jour 9 au jour 13 étaient réelles ou psychologiques.")
	.addField("Annexe 2", "A ce jour, aucun test n'a apporté d'informations supplémentaires concernant la raison pour laquelle la cristallisation se produit. Il ne semble pas y avoir de différences entre SCP-409 et du quartz normal, mis à part ses effets. Le processus de cristallisation de SCP-409 est très semblable à la cristallogenèse, avec laquelle un cristal naturel est ajouté à une solution sursaturée, amenant le cristal à s'\"étendre\" dans la solution. Cependant, SCP-409 semble pouvoir appliquer ce processus sur n'importe quel matériau solide, et ne nécessite pas de rester en contact avec l'objet. Il est, jusqu'à maintenant, impossible de comprendre comment ce processus fonctionne, pourquoi SCP-409 est différent des autres cristaux de quartz, et pourquoi le granit semble être le seul matériau immunisé.")
	message.channel.send(embed)
	//tout doit être dans l'ordre (info puis confinement puis description puis annexe)
	//vous serez cité dans la commande scp/botinfo !
}
